FROM debian:13

LABEL org.opencontainers.image.title="Enterprise Hardened Debian"
LABEL org.opencontainers.image.description="CIS L1-aligned enterprise Debian base image"
LABEL org.opencontainers.image.vendor="Enterprise Hardened Images"
LABEL org.opencontainers.image.source="https://github.com/sm-joe/enterprise-hardened-images"
LABEL org.opencontainers.image.licenses="Internal"
LABEL org.opencontainers.image.base.name="debian:13"